# fortune
# Autogenerated from man page /usr/share/man/man6/fortune.6.gz
complete -c fortune -s a -d 'Choose from all lists of maxims, both offensive and not.  (See the'
complete -c fortune -s o -d 'option for more information on offensive fortunes. )'
complete -c fortune -s c -d 'Show the cookie file from which the fortune came'
complete -c fortune -s e -d 'Consider all fortune files to be of equal size (see discussion below on multi…'
complete -c fortune -s f -d 'Print out the list of files which would be searched, but dont print a fortune'
complete -c fortune -s l -d 'Long dictums only.  See'
complete -c fortune -s n -d 'on how “long” is defined in this sense'
complete -c fortune -s m -d 'Print out all fortunes which match the basic regular expression pattern'
complete -c fortune -l H
complete -c fortune -s s -d 'Short apothegms only.  See'
complete -c fortune -s i -d 'Ignore case for'
complete -c fortune -s w -d 'Wait before termination for an amount of time calculated from the number of c…'

