# keepassxc-cli
# Autogenerated from man page /usr/share/man/man1/keepassxc-cli.1.gz
complete -c keepassxc-cli -l debug-info
complete -c keepassxc-cli -s k -l key-file
complete -c keepassxc-cli -l no-password
complete -c keepassxc-cli -s y -l yubikey
complete -c keepassxc-cli -s q -l quiet
complete -c keepassxc-cli -s h -l help
complete -c keepassxc-cli -s v -l version
complete -c keepassxc-cli -s d -l dry-run
complete -c keepassxc-cli -l key-file-from
complete -c keepassxc-cli -l no-password-from
complete -c keepassxc-cli -l yubikey-from
complete -c keepassxc-cli -s s -l same-credentials
complete -c keepassxc-cli -s u -l username
complete -c keepassxc-cli -l url
complete -c keepassxc-cli -l notes
complete -c keepassxc-cli -s p -l password-prompt
complete -c keepassxc-cli -s g -l generate
complete -c keepassxc-cli -s t -l title
complete -c keepassxc-cli -s a -l advanced
complete -c keepassxc-cli -s H -l hibp
complete -c keepassxc-cli -l okon
complete -c keepassxc-cli -l attribute
complete -c keepassxc-cli -l totp
complete -c keepassxc-cli -s b -l best
complete -c keepassxc-cli -l set-key-file
complete -c keepassxc-cli -l set-password
complete -c keepassxc-cli -l decryption-time
complete -c keepassxc-cli -l unset-password
complete -c keepassxc-cli -l unset-key-file
complete -c keepassxc-cli -l attributes
complete -c keepassxc-cli -l all
complete -c keepassxc-cli -l show-protected
complete -c keepassxc-cli -l show-attachments
complete -c keepassxc-cli -s W -l words
complete -c keepassxc-cli -s w -l word-list
complete -c keepassxc-cli -s f -l format
complete -c keepassxc-cli -s R -l recursive
complete -c keepassxc-cli -l flatten
complete -c keepassxc-cli -s L -l length
complete -c keepassxc-cli -s l -l lower
complete -c keepassxc-cli -s U -l upper
complete -c keepassxc-cli -s n -l numeric
complete -c keepassxc-cli -l special
complete -c keepassxc-cli -s e -l extended
complete -c keepassxc-cli -s x -l exclude
complete -c keepassxc-cli -l exclude-similar
complete -c keepassxc-cli -l every-group

