# keepassxc
# Autogenerated from man page /usr/share/man/man1/keepassxc.1.gz
complete -c keepassxc -s h -l help
complete -c keepassxc -s v -l version
complete -c keepassxc -l config
complete -c keepassxc -l keyfile
complete -c keepassxc -l pw-stdin
complete -c keepassxc -l debug-info

