# vips
# Autogenerated from man page /usr/share/man/man1/vips.1.gz
complete -c vips -s l -l list -d 'List operations below BASE-NAME'
complete -c vips -s p -l plugin -d 'Load PLUGIN.  Note that plugins in $VIPSHOME/lib/vips-plugins-MAJOR'
complete -c vips -s v -l version -d 'Show VIPS version'
complete -c vips -s c -l completion -d 'Print completions for  NAME'

