# vipsthumbnail
# Autogenerated from man page /usr/share/man/man1/vipsthumbnail.1.gz
complete -c vipsthumbnail -s s -l size -d 'Set the output thumbnail size to   N  x   N  pixels'
complete -c vipsthumbnail -s o -l output -d 'Set the output format string'
complete -c vipsthumbnail -s e -l eprofile -d 'Export thumbnails with this ICC profile'
complete -c vipsthumbnail -s i -l iprofile -d 'Import images with this ICC profile, if no profile is embdedded in the image'
complete -c vipsthumbnail -s c -l crop -d 'Crop the output image down'
complete -c vipsthumbnail -s d -l delete -d 'Delete the output profile from the image'
complete -c vipsthumbnail -s t -l rotate -d 'Auto-rotate images using EXIF orientation tags'
complete -c vipsthumbnail -l oprofile -d option
complete -c vipsthumbnail -s a -l linear -d 'Shrink images in linear light colour space.  This can be much slower'

