# vipsheader
# Autogenerated from man page /usr/share/man/man1/vipsheader.1.gz
complete -c vipsheader -s a -l all -d 'Show all fields'
complete -c vipsheader -s f -l field -d 'Print value of  FIELD  from image header'

