# ===========================================================================
# Pyprland Temel Yapılandırması
# ===========================================================================
# -----------------------------
# Aktif Eklentiler
# -----------------------------
[pyprland]
plugins = [
   "scratchpads",           # Hızlı erişim pencereleri
   "lost_windows",          # Kayıp pencereleri bulma
   "monitors",              # Monitör yönetimi
   "shift_monitors",        # Monitör geçişi
   "toggle_dpms",           # Ekran güç yönetimi
   "expose",                # Pencere önizleme
   "workspaces_follow_focus" # Odak takibi
]

# -----------------------------
# Çalışma Alanı Takibi
# -----------------------------
[workspaces_follow_focus]
max_workspaces = 9           # Maksimum çalışma alanı sayısı

# -----------------------------
# Expose Ayarları
# -----------------------------
[expose]
include_special = false      # Özel pencereleri dahil etme

# -----------------------------
# Lost Windows Ayarları
# -----------------------------
[lost_windows]
include_special = false

# -----------------------------
# Shift Monitors Ayarları
# -----------------------------
[shift_monitors]
raise_monitor = true         # Monitör değiştiğinde pencereyi öne getir

# -----------------------------
# Toggle DPMS Ayarları
# -----------------------------
[toggle_dpms]
dpms_timeout = 600          # 10 dakika timeout

## -----------------------------
## Monitör Yapılandırması
## -----------------------------
#[monitors.placement."Dell Inc. DELL UP2716D KRXTR88N909L"]
#topCenterOf = "AU Optronics 0x2036"  # Üst monitörü tam ortaya hizalar
#rate = 59
#resolution = "2560x1440"
#
#[monitors.placement."AU Optronics 0x2036"]
#rate = 60
#resolution = "1920x1080"
##scale = 1.333333
#
#[monitors]
#startup_relayout = true
#new_monitor_delay = 1

# -----------------------------
# Scratchpad Yapılandırmaları
# -----------------------------
# Ses Kontrolü
[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "40% 90%"
unfocus = "hide"
lazy = true

# Terminal Dosya Yöneticisi
[scratchpads.ranger]
animation = "fromTop"
command = "kitty --class ranger ranger"
class = "ranger"
size = "75% 60%"
unfocus = "hide"
lazy = true

# Müzik Oynatıcı
[scratchpads.music]
animation = "fromTop"
command = "spotify"
class = "Spotify"
size = "80% 80%"
unfocus = "hide"
lazy = true

# Terminal
[scratchpads.terminal]
animation = "fromTop"
command = "kitty --class kitty-scratch"
class = "kitty-scratch"
size = "75% 60%"
unfocus = "hide"
lazy = true

# Sistem İzleme
[scratchpads.ncmpcpp]
animation = "fromRight"
command = "__kitty-ncmpcpp.sh"
class = "ncmpcpp"
size = "70% 70%"
unfocus = "hide"
lazy = true

# Not Defteri
[scratchpads.notes]
animation = "fromBottom"
command = "kitty --class notes nvim"
class = "notes"
size = "70% 50%"
unfocus = "hide"
lazy = true
