# Font konfigürasyonu
[font]
size = 12.8                # Font boyutu
builtin_box_drawing = true # Yerleşik box-drawing karakterlerini kullan

# Normal font ayarları
[font.normal]
family = "JetBrains Mono"
style = "Regular"

# Kalın font ayarları
[font.bold]
family = "JetBrains Mono"
style = "Bold"

# İtalik font ayarları
[font.italic]
family = "JetBrains Mono"
style = "Italic"

# Kalın italik font ayarları
[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

# Font konumlandırma ayarları
[font.offset]
x = 0  # Yatay offset
y = 1  # Dikey offset - JetBrains Mono için hafif yukarı ayarlandı

# Glyph konumlandırma ayarları
[font.glyph_offset]
x = 0  # Yatay glyph offset
y = 0  # Dikey glyph offset
